name: Restrict PR Sources

on:
  pull_request:
    branches:
      - master

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce branch source rules
        run: |
          if [[ "${GITHUB_BASE_REF}" == "master" && "${GITHUB_HEAD_REF}" != "develop" ]]; then
            echo "❌ PRs to master must come from develop only."
            exit 1
          fi

          echo "✅ PR source is valid."
